---

### Django ###
django_dir: '{{ api_src_dir }}'
django_wsgi_file: '{{ django_dir }}/{{ deploy_app_name }}/wsgi.py'
django_settings: '{{ deploy_app_name }}.settings'
django_static_url: '/static'
django_static_root: '{{ django_dir }}/collected_static'
django_local_settings_file: '{{ django_dir }}/local_settings.py'
django_local_settings: "{{ lookup('template', playbook_dir + '/files/local_settings.py.j2') }}"
django_fixtures:
 - '{{ django_dir }}/fixtures/initial_data.json'
