---

### PostgreSQL ###
postgresql_version: 9.5
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'
postgresql_cluster_name: 'main'

postgresql_admin_user: 'postgres'
postgresql_default_auth_method: 'trust'

postgresql_listen_addresses:
  - 'localhost'
postgresql_port: 5432

# NOTICE! For public projects put your `vaulted_*` variables into `vault.yml` and ecrypt them!

postgresql_databases:
  - name: '{{ vaulted_database_name }}'

postgresql_users:
  - name: '{{ vaulted_database_user }}'
    pass: '{{ vaulted_database_password }}'
    encrypted: no # denotes if the password is already encrypted.

postgresql_user_privileges:
  - name: '{{ vaulted_database_user }}'
    db: '{{ vaulted_database_name }}'
    priv: 'ALL'
