---
vaulted_database_name: 'boilerplate'
vaulted_database_user: 'boilerplate'
vaulted_database_password: 'boilerplate'

### Postres (Private) ###
postgresql_listen_addresses:
  - 'localhost'
postgresql_port: 5432

postgresql_databases:
  - name: '{{ vaulted_database_name }}'

postgresql_users:
  - name: '{{ vaulted_database_user }}'
    pass: '{{ vaulted_database_password }}'
    encrypted: no # denotes if the password is already encrypted.

postgresql_user_privileges:
  - name: '{{ vaulted_database_user }}'
    db: '{{ vaulted_database_name }}'
    priv: 'ALL'
    role_attr_flags: 'SUPERUSER'


### Environment ###
environment_variables:
  NODE_ENV: 'development'

  DEBUG: True
  DJANGO_SETTINGS_MODULE: '{{ deploy_app_name }}.settings'
  SECRET_KEY: 'super-secure-hash'
  PYTHONHASHSEED: 1234

  DATABASE_HOST: 'localhost'
  DATABASE_PORT: 5432
  DATABASE_NAME: '{{ vaulted_database_name }}'
  DATABASE_USER: '{{ vaulted_database_user }}'
  DATABASE_PASSWORD: '{{ vaulted_database_password }}'

  CACHE_DEFAULT_LOCATION: 'redis://127.0.0.1:6379/1'
  CACHE_CELERY_LOCATION: 'redis://127.0.0.1:6379/2'
  CACHE_CELERY_RESULT_LOCATION: 'redis://127.0.0.1:6379/3'


### Deploy ###
deploy_env: development
force_upgrade: yes

### Project ###
cacheservers_internal: yes
dbservers_internal: yes
skip_checkout: yes

### Domains ###
site_domain: 'boilerplate.local'
api_domain: 'api.{{ site_domain }}'
flower_domain: 'flower.{{ site_domain }}'
tornado_domain: 'ws.{{ site_domain }}'
docs_domain: 'docs.{{ site_domain }}'

