---
- name: Tornado | Generate upstart scripts
  become: yes
  template:
    src: 'tornado.conf.j2'
    dest: '/etc/init/{{ deploy_app_name }}-tornado.conf'
    owner: root
    group: root
    mode: 0644
  notify:
    - restart tornado