---
- name: Configuring environment variables
  lineinfile:
    dest: "{{ environment_file }}"
    line: '{{ item.key }}="{{ item.value }}"'
  with_dict: environment_variables
  register: environment_variables_status
  when: environment_variables is defined